### ISSUE TITLE
epic: Built-in Model Library

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/models#21]
### Model Library
- [ ] Work with eng team to update URLs
- [ ] Update READMEs
- [ ] Provide more quantizations (e.g. full llama.cpp quantizations)
- [ ] Document how to create/add a Model Library 
- [x] https://github.com/janhq/cortex.so/issues/78
- [ ] [TBD] Shift Built-in model repos back to Jan's huggingface (better brand recognition, we are also not pushing Cortex as a brand for now)

### Models

- [ ] https://github.com/janhq/models/issues/17
- [ ] https://github.com/janhq/models/issues/16
- [ ] https://github.com/janhq/models/issues/19
- [x] https://github.com/janhq/cortex.cpp/issues/1340
