### ISSUE TITLE
chore: clean up Hugging Face Repos old files, future default branches

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/models#48]
## Task list
- [x] Delete old .gguf and metadata.yaml files from main branch
- [x] Update default branches in metadata.yml for some models https://github.com/janhq/cortex.cpp/issues/1418#issuecomment-2392716451

## Ongoing discussion: 
- [x] remove `id` from model.yml? janhq/cortex.cpp#1410

**Comment by hahuyhoang411** [comment]
Finished remove all of the gguf files in main branch

**Comment by gabrielle-ong** [comment]
Thank you so much @hahuyhoang411 <3
